apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: spark-operator
data:
  spark-defaults.conf: |
    spark.sql.extensions                               org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    spark.sql.catalog.spark_catalog                    org.apache.iceberg.spark.SparkCatalog
    spark.sql.catalog.spark_catalog.type               hive
    spark.sql.catalogImplementation                    hive
    spark.sql.catalog.spark_catalog.warehouse          s3a://warehouse
    spark.sql.warehouse.dir                            s3a://warehouse
    spark.hadoop.hive.metastore.uris                   thrift://hive-metastore.hq-engine.svc.cluster.local:9083
    spark.hadoop.fs.s3a.access.key                     minio_access_key
    spark.hadoop.fs.s3a.secret.key                     minio_secret_key
    spark.hadoop.fs.s3a.endpoint                       http://minio.big-storage.svc.cluster.local:9000
    spark.hadoop.fs.s3a.impl                           org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.path.style.access              true
    spark.hadoop.fs.s3a.connection.ssl.enabled         false