apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sparkoperator
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v1beta2-1.3.0-3.1.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/version: v1beta2-1.3.0-3.1.1
  serviceName: sparkoperator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v1beta2-1.3.0-3.1.1
    spec:
      serviceAccountName: sparkoperator
      containers:
      - name: sparkoperator
        image: duynguyenngoc/spark-operator:3.5.1
        imagePullPolicy: Always
        args:
        - -logtostderr
        volumeMounts:
        - name: spark-config
          mountPath: /opt/spark/conf
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
