version: '3.8'
services:

  spark:
    image: bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src

  spark-worker:
    image: bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data
      - ./src:/src

  spark-worker2:
    image: bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - '8082:8081'  # Use a different port to avoid conflicts
    volumes:
      - ./data:/data
      - ./src:/src

  jupyterlab:
    image: streamingpipeline/big-data:py311-jupyterlab-latest
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
      - ./src:/app